// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RoamingClipboardDataLayerMig;
using System;

namespace RoamingClipboardDataLayerMig.Migrations
{
    [DbContext(typeof(DesignerDbContext))]
    [Migration("20180220120114_InitialDatabaseSchema")]
    partial class InitialDatabaseSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RoamingClipboardDataLayer.Category", b =>
                {
                    b.Property<Guid>("IDCategory")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryDescription");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateLastAssignedTo");

                    b.Property<DateTime>("DateLastEdited");

                    b.HasKey("IDCategory");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RoamingClipboardDataLayer.Link", b =>
                {
                    b.Property<Guid>("IDLink")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BestBefore");

                    b.Property<Guid?>("CategoryIDCategory");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastEdited");

                    b.Property<string>("Description");

                    b.Property<string>("UrlString")
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("IDLink");

                    b.HasIndex("CategoryIDCategory");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("RoamingClipboardDataLayer.Link", b =>
                {
                    b.HasOne("RoamingClipboardDataLayer.Category", "Category")
                        .WithMany("Links")
                        .HasForeignKey("CategoryIDCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
