// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RoamingClipboardDataLayer.Migration;
using System;

namespace RoamingClipboardDataLayer.Migration.Migrations
{
    [DbContext(typeof(DesignerDbContext))]
    [Migration("20180217103414_InitialSchemaDefinition")]
    partial class InitialSchemaDefinition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RoamingClipboardDataLayer.Category", b =>
                {
                    b.Property<Guid>("IdCategory")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("DateCreated");

                    b.Property<DateTimeOffset>("DateLastAssignedTo");

                    b.Property<DateTimeOffset>("DateLastEdited");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RoamingClipboardDataLayer.Link", b =>
                {
                    b.Property<Guid>("IdLink")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan?>("BestBefore");

                    b.Property<Guid?>("CategoryIdCategory");

                    b.Property<DateTimeOffset>("DateCreated");

                    b.Property<DateTimeOffset>("DateLastEdited");

                    b.Property<string>("Description");

                    b.Property<string>("UrlString")
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("IdLink");

                    b.HasIndex("CategoryIdCategory");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("RoamingClipboardDataLayer.Link", b =>
                {
                    b.HasOne("RoamingClipboardDataLayer.Category", "Category")
                        .WithMany("Links")
                        .HasForeignKey("CategoryIdCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
